name: GitHub pages

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install deps
              run: bun i

            - name: Build sudoku app
              run: bun run build

            - name: Deploy demo
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/
